services:
  db:
    image: postgres:16
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: ecommerce_api
    command: >
      sh -c "
      until pg_isready -h db -p 5432; do
        echo 'Waiting for database...';
        sleep 1;
      done;
      python manage.py migrate &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=ecommerce
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: